services:
  - type: web
    name: evoting-portal
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: AES_KEY
        generateValue: true
